#pragma once

#include "SetPeriodicCoolTime.h"
#include "SetTreeCooldown.h"
#include "WaitForDelay.h"
#include "GroggyAction.h"
#include "TeleportAction.h"
#include "Pattern1Action.h"
#include "Pattern2Action.h"
#include "Pattern3Action.h"
#include "Pattern4Action.h"
#include "Pattern5Action.h"
#include "Pattern6Action.h"
#include "Pattern7Action.h"
#include "Pattern8Action.h"
#include "Pattern9Action.h"
#include "Pattern10Action.h"
#include "Pattern11Action.h"
#include "Pattern12Action.h"
#include "Pattern13Action.h"

